title: "Yeseon Hong"
email: "ghddptjs@sogang.ac.kr"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nassunii.github.io" # the base hostname & protocol
twitter_username: ""
github_username: "nassunii"
linkedin_username: "yeseon-hong-753200345"
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: ["README.md", "node_modules", "package.json", "package-lock.json"]
