
title: Yeseon Hong
email: ghddptjs@cau.ac.kr
description: >-
  AI Researcher at Chung-Ang University. Interested in LLMs, Human-AI Interaction, and Vision-Language Models.
baseurl: "" 
url: "https://nassunii.github.io"
theme: minima
markdown: kramdown
